1\. **PCA on 3D dataset**

* Generate a dataset simulating 3 features, each with N entries (N being ${\cal O}(1000)$). Each feature is made by random numbers generated according the normal distribution $N(\mu,\sigma)$ with mean $\mu_i$ and standard deviation $\sigma_i$, with $i=1, 2, 3$. Generate the 3 variables $x_{i}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues using the eigendecomposition of the covariance matrix
* Find the eigenvectors and eigenvalues using the SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained
* Redefine the data according to the new basis from the PCA
* Plot the data, in both the original and the new basis. The figure should have 2 rows (the original and the new basis) and 3 columns (the $[x_0, x_1]$, $[x_0, x_2]$ and $[x_1, x_2]$ projections) of scatter plots.

In [1]:
import numpy as np
from scipy import linalg as la
from matplotlib import pyplot as plt

In [2]:
####################### GENERATING DATASET ##########################################################

#Generating a dataset simulating 3 features each with N=1000 entries
#Each feature is made by random numbers according to the normal distrubiton with given mean and standard deviation
#Features can be created as follows:
#====> x1 with mean 0 and std 1
#====> x2 = x1 + with mean 0 and std 3
#====> x3 = 2x1 + x2

def GenerateThreeFeatureDataset(meanx1,meanx2,meanx3,stdx1,stdx2,stdx3,N):
    
    #Generation of the features as normal distrubitons with given mean,standard deviation and amount
    x1 = np.random.normal(meanx1,stdx1,N)
    x2 = x1 + np.random.normal(meanx2,stdx2,N)
    x3 = (2*x1) + x2
    
    #Packing the features, generating the required dataset
    #There will be 3 rows and 1000 columns
    #Resultant will be returned from the function
    
    dataset = np.array([x1,x2,x3])
    return dataset
##############################################################################################
meanx1=0
meanx2=0
meanx3=0
stdx1=1
stdx2=2
stdx3=3
N=1000
dataset = GenerateThreeFeatureDataset(meanx1,meanx2,meanx3,stdx1,stdx2,stdx3,N)
################## EIGEN DECOMPOSITION OF THE COVARIANCE MATRIX ##############################

#Find the eigenvectors and eigenvalues using the eigen decomposition of the covariance matrix

def EigenDecompositionOfCovarianceMatrix(dataset):
    
    #MeanVector = np.mean(dataset, axis=0)
    # the covariance matrix
    #dataset = dataset - MeanVector
    covarianceMatrix = np.cov(dataset)
    #covarianceMatrix = np.dot(dataset, dataset.T)/(dataset.shape[0]-1)
    #print(np.allclose(cova, covarianceMatrix)) # Should return True
    #covarianceMatrixOne = np.dot(dataset, dataset.T)/(dataset.shape[0]-1) # this would yield the same result
    print("Covariance matrix:\n", covarianceMatrix, '\n')
    
    # now find the eigenvectors and eigenvalues of the covariance matrix
    eigenValues, eigenVectors = la.eig(covarianceMatrix)
    
    # take only the real component, if possible
    eigenValues = np.real_if_close(eigenValues)
    
    print("Eigenvalues from the EigenDecomposition:\n", eigenValues, '\n')
    print("Eigenvectors from the EigenDecomposition:\n", eigenVectors, '\n')
    print("Shape of the Eigenvalues from the EigenDecomposition:\n",eigenValues.shape,"\n")
    print("Shape of the EigenVectors from the EigenDecomposition:\n",eigenVectors.shape,"\n")
    
    return eigenValues,eigenVectors,covarianceMatrix

################################################################################################
eigenValues , eigenVectors, covarianceMatrix  = EigenDecompositionOfCovarianceMatrix(dataset)
    
############################## SINGULAR VALUE DECOMPOSITION(SVD) ####################################
def SingularValueDecomposition(dataset):
    #Find the eigenvectors and eigenvalues using the SVD
    # perform the SVD

    #Some knowledge
    #UnitaryMatrixRows is a 1000x1000 orthogonal,unitary matrix
    #UnitaryMatrixColumnsTranspose is a 3x3 orthogonal, unitary matrix
    #Spectrum rectangular, diagonal matrix with shape mxn

    U, s, Vt = la.svd(dataset)

    #print("Shapes: U =", UnitaryMatrixRows.shape, "S:", Spectrum.shape, "V^T:", UnitaryMatrixColumnsTranspose.shape, '\n')
    #print("Spectrum Matrix:\n", Spectrum, '\n')
    #print("Unitary Matrix U:\n", UnitaryMatrixRows, '\n')
    #print("Transpose of Unitary Matrix V:\n", UnitaryMatrixColumnsTranspose, '\n')
    
    #ev = np.square(Spectrum) / (dataset.shape[0] - 1)
    ###### Eigen vectors are the columns of the Unitary Matrix ####################
    print("Eigenvectors from SVD:\n",U, '\n')
    ###### Eigen values are the valuses in the diagonal of the Spectrum Matrix ####
    print("Eigenvalues from SVD:\n", s, '\n')
    print("Shape of the Eigenvalues from the SVD:\n",s.shape,"\n")
    print("Shape of the EigenVectors from the SVD:\n",U.shape,"\n")
    return U,s
##################################################################################################

U , s = SingularValueDecomposition(dataset)
############# CHECK WHETHER BOTH EIGENVECTORS AND EIGENVALUES ARE SAME ###########################

print(np.allclose(s, eigenValues)) # Should return True
print(np.allclose(U, eigenVectors)) # Should return True

Covariance matrix:
 [[ 0.97466393  1.06222618  3.01155404]
 [ 1.06222618  5.2695143   7.39396666]
 [ 3.01155404  7.39396666 13.41707473]] 

Eigenvalues from the EigenDecomposition:
 [ 1.83509041e+01 -2.00753097e-16  1.31034886e+00] 

Eigenvectors from the EigenDecomposition:
 [[-0.17766473 -0.81649658  0.54933467]
 [-0.49513009 -0.40824829 -0.76692863]
 [-0.85045955  0.40824829  0.3317407 ]] 

Shape of the Eigenvalues from the EigenDecomposition:
 (3,) 

Shape of the EigenVectors from the EigenDecomposition:
 (3, 3) 

Eigenvectors from SVD:
 [[-0.1776646   0.54933471 -0.81649658]
 [-0.49513027 -0.76692851 -0.40824829]
 [-0.85045947  0.33174091  0.40824829]] 

Eigenvalues from SVD:
 [1.35397770e+02 3.61807184e+01 4.95306262e-14] 

Shape of the Eigenvalues from the SVD:
 (3,) 

Shape of the EigenVectors from the SVD:
 (3, 3) 

False
False
